### PR TITLE
Add message and details to the failed assertion 

### PR DESCRIPTION
**Pull request by revir**
# Change Type

* [x] Feature
* [ ] Chore
* [ ] Bug Fix

# Change Level

* [ ] major
* [ ] minor
* [x] patch

# Further Information (screenshots, bug report links, etc.)

# Checklist

* [x] Added tests / did not decrease code coverage
* [ ] Tested in supported environments (common browsers or current and LTS Node)

### CODE REVIEW

**Comment by zautumnz** [comment]
I no longer use TeamCity, so I'm just going to trust that this works :)

**Comment by zautumnz** [comment]
There's a failing test, so I reverted in master, but will get it fixed this evening and released.

**Comment by zautumnz** [comment]
Turns out I'm not doing much today, so I had time this morning. Published in v4.4.0. Thank you for the enhancements.

**Comment by revir** [comment]
Great, thanks!

**Pull request merged**
